language: python
python: "3.6"
install:
  - pip install transcrypt
script:
  - transcrypt -b -e 6 cmtq_web.py
branches:
  only:
    - master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
